import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English'); // 'English' or 'Arabic'

  const toggleLanguage = () => {
    setLanguage(language === 'English' ? 'Arabic' : 'English');
  };

  // Translation dictionary
  const translations = {
    // Welcome Screen
    'Welcome to Bridge-IT': 'مرحباً بك في Bridge-IT',
    'Hello': 'مرحباً',
    'Sign in to your account': 'سجل الدخول إلى حسابك',
    'Sign in to continue': 'سجل الدخول للمتابعة',
    'Email': 'البريد الإلكتروني',
    'Password': 'كلمة المرور',
    'Sign in': 'تسجيل الدخول',
    'SIGN IN': 'تسجيل الدخول',
    'SIGNING IN...': 'جاري تسجيل الدخول...',
    'Signing in...': 'جاري تسجيل الدخول...',
    'Forgot your Password?': 'نسيت كلمة المرور؟',
    'Forgot password?': 'نسيت كلمة المرور؟',
    'Need an account? ': 'تحتاج حساب؟ ',
    'CREATE AN ACCOUNT': 'إنشاء حساب',
    'Sign up': 'إنشاء حساب',

    // Registration Screen
    'Create your account': 'إنشاء حسابك',
    'Back to sign in': 'العودة لتسجيل الدخول',
    'First Name': 'الاسم الأول',
    'Last Name': 'اسم العائلة',
    'Age': 'العمر',
    'Phone Number': 'رقم الهاتف',
    'Confirm Password': 'تأكيد كلمة المرور',
    'Create Account': 'إنشاء الحساب',
    'Please fill in all fields': 'يرجى ملء جميع الحقول',
    'Password must be at least 8 characters': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    'Passwords do not match': 'كلمات المرور غير متطابقة',
    'Age must be at least 18 years old': 'يجب أن يكون العمر 18 سنة على الأقل',
    'Account created successfully!': 'تم إنشاء الحساب بنجاح!',

    // Questionnaire Screen
    'Questionnaire': 'الاستبيان',
    'CV Upload': 'رفع السيرة الذاتية',
    'Please enter your credentials and resume': 'يرجى إدخال بياناتك والسيرة الذاتية',
    'Upload CV/Resume': 'رفع السيرة الذاتية/البيانات',
    'Uploaded Files:': 'الملفات المرفوعة:',
    'Skip CV Upload': 'تخطي رفع السيرة الذاتية',
    'Getting to know you...': 'نتعرف عليك...',
    'Complete': 'مكتمل',
    'Next': 'التالي',
    'Finish Registration': 'إنهاء التسجيل',
    'Please answer the question before continuing.': 'يرجى الإجابة على السؤال قبل المتابعة.',
    'Failed to upload file. Please try again.': 'فشل في رفع الملف. يرجى المحاولة مرة أخرى.',
    'Registration completed successfully!': 'تم إكمال التسجيل بنجاح!',
    'AI recommends these courses and jobs based on your profile!': 'يوصي الذكاء الاصطناعي بهذه الدورات والوظائف بناءً على ملفك الشخصي!',
    'Bridge-IT AI Analysis': 'تحليل Bridge-IT الذكاء الاصطناعي',
    'Bridge-IT AI takes the information from this questionnaire to build up your profile and advise you on courses and jobs that match your skills and goals.': 'يأخذ Bridge-IT الذكاء الاصطناعي المعلومات من هذا الاستبيان لبناء ملفك الشخصي ونصحك بالدورات والوظائف التي تناسب مهاراتك وأهدافك.',
    'Start Questionnaire': 'ابدأ الاستبيان',
    'AI Recommendations': 'توصيات الذكاء الاصطناعي',
    'These courses are recommended by our AI based on your profile': 'هذه الدورات موصى بها من قبل ذكائنا الاصطناعي بناءً على ملفك الشخصي',
    'These jobs are recommended by our AI based on your profile': 'هذه الوظائف موصى بها من قبل ذكائنا الاصطناعي بناءً على ملفك الشخصي',
    'Building your personalized recommendations': 'بناء توصياتك الشخصية',
    'Analyzing your profile...': 'تحليل ملفك الشخصي...',
    'Searching for relevant courses...': 'البحث عن الدورات ذات الصلة...',
    'Finding matching job opportunities...': 'البحث عن فرص العمل المناسبة...',
    'Generating personalized recommendations...': 'إنشاء توصيات شخصية...',
    'Please wait while we analyze your profile...': 'يرجى الانتظار بينما نحلل ملفك الشخصي...',
    'No job recommendations yet': 'لا توجد توصيات وظائف بعد',
    'Complete the questionnaire to get personalized job recommendations': 'أكمل الاستبيان للحصول على توصيات وظائف شخصية',
    'No course recommendations yet': 'لا توجد توصيات دورات بعد',
    'Complete the questionnaire to get personalized course recommendations': 'أكمل الاستبيان للحصول على توصيات دورات شخصية',
    'Hey there, what are you looking for?': 'مرحباً، ماذا تبحث عنه؟',
    'Looking for a new career': 'البحث عن مهنة جديدة',
    'Continuing my education': 'متابعة تعليمي',
    'Finding a job in my field of expertise': 'البحث عن وظيفة في مجال تخصصي',
    'Receiving new certification': 'الحصول على شهادة جديدة',
    'Other': 'أخرى',
    'Where do you live in the west bank?': 'أين تعيش في الضفة الغربية؟',
    'What is your current employment status?': 'ما هو وضعك الوظيفي الحالي؟',
    'Employed but not satisfied with my salary': 'موظف ولكن غير راضٍ عن راتبي',
    'Employed but not in my field of study': 'موظف ولكن ليس في مجال دراستي',
    'Recently laid off (up to 3 months)': 'تم تسريحي مؤخراً (حتى 3 أشهر)',
    'Unemployed for more than 3 months': 'عاطل عن العمل لأكثر من 3 أشهر',
    'Never was employed before': 'لم أعمل من قبل',
    'What Prior Experience do you have?': 'ما هي الخبرة السابقة لديك؟',
    'Bachelor\'s or Undergraduate': 'بكالوريوس أو بكالوريوس',
    'Higher form of Education': 'شكل أعلى من التعليم',
    'Field Experience': 'الخبرة الميدانية',
    'High school Diploma': 'دبلوم المدرسة الثانوية',
    'Internship': 'التدريب',
    'vocational training': 'التدريب المهني',
    'What university did you attended?': 'أي جامعة التحقت بها؟',
    'I didn\'t attend university': 'لم ألتحق بالجامعة',
    'What field/s is your experience in? (multiple answer)': 'في أي مجال/مجالات خبرتك؟ (إجابة متعددة)',
    'What field/s do you wish to work in? (multiple answer)': 'في أي مجال/مجالات ترغب في العمل؟ (إجابة متعددة)',
    'Social & Behavioural Sciences': 'العلوم الاجتماعية والسلوكية',
    'What is your dream job?': 'ما هي وظيفة أحلامك؟',
    'Describe your dream job...': 'صف وظيفة أحلامك...',
    'In what countries are you interested in working remotely?': 'في أي دول تهتم بالعمل عن بُعد؟',
    'Please specify...': 'يرجى التحديد...',

    // Dashboard/Home Screen
    'Home': 'الرئيسية',
    'Profile': 'الملف الشخصي',
    'Logout': 'تسجيل الخروج',
    'Welcome': 'مرحباً',
    'Your career hub is ready.': 'مركز حياتك المهنية جاهز.',
    'Jobs': 'الوظائف',
    'Courses': 'الدورات',
    'View Details': 'عرض التفاصيل',
    'AI suggestions refreshed and shuffled!': 'تم تحديث وخلط اقتراحات الذكاء الاصطناعي!',

    // Profile Screen
    'Your Profile': 'ملفك الشخصي',
    'Manage your information and preferences.': 'إدارة معلوماتك وتفضيلاتك.',
    'Personal Details': 'التفاصيل الشخصية',
    'Edit': 'تعديل',
    'Full Name': 'الاسم الكامل',
    'Phone': 'الهاتف',
    'Location': 'الموقع',
    'University': 'الجامعة',
    'ICT Specialization': 'التخصص في تكنولوجيا المعلومات والاتصالات',
    'Job Interests': 'الاهتمامات الوظيفية',
    'Questionnaire Answers': 'إجابات الاستبيان',
    'Technology/IT': 'التكنولوجيا/تكنولوجيا المعلومات',
    'Business/Finance': 'الأعمال/المالية',
    'Your responses from the registration questionnaire.': 'استجاباتك من استبيان التسجيل.',
    'Career Goal': 'الهدف المهني',
    'Region': 'المنطقة',
    'Experience Level': 'مستوى الخبرة',
    'Field of Experience': 'مجال الخبرة',
    'Languages': 'اللغات',
    'Retake Questionnaire': 'إعادة الاستبيان',
    'AI Analyst': 'محلل الذكاء الاصطناعي',
    'Retake the survey or refresh your recommendations based on your latest profile updates.': 'أعد الاستبيان أو حدث توصياتك بناءً على آخر تحديثات ملفك الشخصي.',
    'Refresh AI Suggestions': 'تحديث اقتراحات الذكاء الاصطناعي',
    'Edit Profile': 'تعديل الملف الشخصي',
    'Enter your full name': 'أدخل اسمك الكامل',
    'Enter your email': 'أدخل بريدك الإلكتروني',
    'Enter your phone number': 'أدخل رقم هاتفك',
    'Enter your location': 'أدخل موقعك',
    'Enter your university': 'أدخل جامعتك',
    'Enter your degree': 'أدخل درجتك العلمية',
    'Enter your specialization': 'أدخل تخصصك',
    'Save Changes': 'حفظ التغييرات',
    'Cancel': 'إلغاء',
    'Success': 'نجح',
    'Not specified': 'غير محدد',
    'Profile updated successfully!': 'تم تحديث الملف الشخصي بنجاح!',
    'Permission Required': 'الإذن مطلوب',
    'Please grant photo library permissions to upload a profile image.': 'يرجى منح أذونات مكتبة الصور لتحميل صورة الملف الشخصي.',
    'Profile image updated successfully!': 'تم تحديث صورة الملف الشخصي بنجاح!',
    'Are you sure you want to logout?': 'هل أنت متأكد من أنك تريد تسجيل الخروج؟',
    'AI suggestions refreshed!': 'تم تحديث اقتراحات الذكاء الاصطناعي!',
    'John Doe': 'جون دو',
    'Search courses...': 'البحث في الدورات...',
    'Search jobs...': 'البحث في الوظائف...',
    'No courses found matching your search': 'لم يتم العثور على دورات تطابق بحثك',
    'No jobs found matching your search': 'لم يتم العثور على وظائف تطابق بحثك',
    'Try adjusting your search terms': 'حاول تعديل مصطلحات البحث',
    'Calendar': 'التقويم',
    'Day': 'اليوم',
    'Week': 'الأسبوع',
    'Month': 'الشهر',
    'Calendar View': 'عرض التقويم',
    'Calendar functionality coming soon': 'وظائف التقويم قريباً',
    'Add Event': 'إضافة حدث',
    'Event title': 'عنوان الحدث',
    'Description (optional)': 'الوصف (اختياري)',
    'Add': 'إضافة',
    'Event': 'حدث',
    'Note': 'ملاحظة',
    'Today': 'اليوم',
    'Delete Event': 'حذف الحدث',
    'Are you sure you want to delete this event?': 'هل أنت متأكد من أنك تريد حذف هذا الحدث؟',
    'Delete': 'حذف',
    'Cancel': 'إلغاء',
    'No events for this day': 'لا توجد أحداث لهذا اليوم',
    'Time (optional)': 'الوقت (اختياري)',

    // Settings Screen
    'Settings': 'الإعدادات',
    'Dark Mode': 'الوضع المظلم',
    'Toggle dark mode': 'تبديل الوضع المظلم',
    'Language': 'اللغة',
    'Switch between English and Arabic': 'التبديل بين الإنجليزية والعربية',
    'App Settings': 'إعدادات التطبيق',
    'Customize your experience': 'خصص تجربتك',
    'Switch between light and dark themes': 'التبديل بين السمات الفاتحة والداكنة',
    'Notifications': 'الإشعارات',
    'Manage your notification preferences': 'إدارة تفضيلات الإشعارات',
    'Privacy & Security': 'الخصوصية والأمان',
    'Manage your privacy and security settings': 'إدارة إعدادات الخصوصية والأمان',
    'Help & Support': 'المساعدة والدعم',
    'Get help and contact support': 'احصل على المساعدة واتصل بالدعم',
    'About': 'حول',
    'App version and information': 'إصدار التطبيق والمعلومات',

    // Job Details
    'Job Details': 'تفاصيل الوظيفة',
    'Company': 'الشركة',
    'Location': 'الموقع',
    'Work Type': 'نوع العمل',
    'Level': 'المستوى',
    'Salary': 'الراتب',
    'Category': 'الفئة',
    'Description': 'الوصف',
    'Why This Job Suits You': 'لماذا تناسبك هذه الوظيفة',
    'Matching Skills': 'المهارات المتطابقة',
    'Requirements': 'المتطلبات',
    'Apply Now': 'تقدم الآن',
    'Your background and skills align perfectly with this role. The company values candidates with your experience level.': 'خلفيتك ومهاراتك تتوافق تماماً مع هذا الدور. الشركة تقدر المرشحين بمستوى خبرتك.',
    'Your cybersecurity background and technical skills align perfectly with this role. The company values candidates with your experience level.': 'خلفيتك في الأمن السيبراني ومهاراتك التقنية تتوافق تماماً مع هذا الدور. الشركة تقدر المرشحين بمستوى خبرتك.',

    // Job Titles and Categories
    'Network Security Specialist': 'متخصص أمن الشبكات',
    'Cybersecurity Analyst': 'محلل الأمن السيبراني',
    'Data Scientist': 'عالم البيانات',
    'Data Analyst': 'محلل البيانات',
    'Cybersecurity': 'الأمن السيبراني',
    'Data Science': 'علم البيانات',
    'On-site': 'في الموقع',
    'Remote': 'عن بُعد',
    'Mid Level': 'مستوى متوسط',
    'Senior Level': 'مستوى متقدم',
    'Entry Level': 'مستوى مبتدئ',

    // Job Descriptions
    'Protect our clients\' digital infrastructure and implement advanced security measures to safeguard against cyber threats.': 'حماية البنية التحتية الرقمية لعملائنا وتنفيذ تدابير أمنية متقدمة لحماية ضد التهديدات السيبرانية.',
    'Your background in cybersecurity and analytical skills make you an ideal candidate for this position.': 'خلفيتك في الأمن السيبراني ومهاراتك التحليلية تجعلك مرشحاً مثالياً لهذا المنصب.',
    'Analyze business data and create predictive models to drive strategic decisions and improve operational efficiency.': 'تحليل بيانات الأعمال وإنشاء نماذج تنبؤية لدفع القرارات الاستراتيجية وتحسين الكفاءة التشغيلية.',
    'Your data analysis skills and technical background make you a perfect fit for this role.': 'مهاراتك في تحليل البيانات وخلفيتك التقنية تجعلك مناسباً تماماً لهذا الدور.',
    'Analyze business data and create insights to help organizations make data-driven decisions.': 'تحليل بيانات الأعمال وإنشاء رؤى لمساعدة المؤسسات على اتخاذ قرارات مدفوعة بالبيانات.',
    'Your analytical skills and attention to detail make you an excellent candidate for this position.': 'مهاراتك التحليلية والاهتمام بالتفاصيل تجعلك مرشحاً ممتازاً لهذا المنصب.',

    // Job Skills
    'Network Security': 'أمن الشبكات',
    'Problem-solving': 'حل المشكلات',
    'Threat Analysis': 'تحليل التهديدات',
    'Security Tools': 'أدوات الأمان',
    'Machine Learning': 'التعلم الآلي',
    'Python': 'بايثون',
    'Excel': 'إكسل',
    'SQL': 'إس كيو إل',

    // Job Requirements
    'Bachelor\'s degree in Computer Science or related field': 'بكالوريوس في علوم الحاسوب أو مجال ذي صلة',
    'Experience with network security protocols': 'خبرة في بروتوكولات أمن الشبكات',
    'Knowledge of cybersecurity tools and practices': 'معرفة بأدوات وممارسات الأمن السيبراني',
    'Strong analytical and problem-solving skills': 'مهارات تحليلية قوية ومهارات حل المشكلات',
    'Master\'s degree in Cybersecurity or related field': 'ماجستير في الأمن السيبراني أو مجال ذي صلة',
    'Experience with threat detection and response': 'خبرة في اكتشاف التهديدات والاستجابة',
    'Knowledge of security frameworks and compliance': 'معرفة بأطر العمل الأمنية والامتثال',
    'Excellent communication and reporting skills': 'مهارات ممتازة في التواصل والتقرير',
    'Master\'s degree in Data Science or related field': 'ماجستير في علم البيانات أو مجال ذي صلة',
    'Experience with machine learning algorithms': 'خبرة في خوارزميات التعلم الآلي',
    'Proficiency in Python, R, and SQL': 'إتقان بايثون و آر و إس كيو إل',
    'Strong statistical analysis skills': 'مهارات قوية في التحليل الإحصائي',
    'Bachelor\'s degree in Statistics, Mathematics, or related field': 'بكالوريوس في الإحصاء أو الرياضيات أو مجال ذي صلة',
    'Experience with data visualization tools': 'خبرة في أدوات تصور البيانات',
    'Proficiency in Excel and SQL': 'إتقان إكسل وإس كيو إل',

    // Course Details
    'Course Details': 'تفاصيل الدورة',
    'Provider': 'المزود',
    'Delivery': 'طريقة التوصيل',
    'Duration': 'المدة',
    'Level': 'المستوى',
    'Price': 'السعر',
    'Why This Course Will Help You': 'لماذا ستساعدك هذه الدورة',
    'Skills You\'ll Develop': 'المهارات التي ستطورها',
    'Course Description': 'وصف الدورة',
    'Course Outline': 'مخطط الدورة',
    'Prerequisites': 'المتطلبات المسبقة',
    'Enroll Now': 'سجل الآن',
    'This course is designed to enhance your skills and knowledge in the field. It\'s perfect for your current experience level and career goals.': 'تم تصميم هذه الدورة لتعزيز مهاراتك ومعرفتك في المجال. إنها مثالية لمستوى خبرتك الحالي وأهدافك المهنية.',

    // Course Titles
    'Data Science with Python': 'علم البيانات مع بايثون',
    'Cybersecurity Fundamentals': 'أساسيات الأمن السيبراني',
    'Mobile App Development (React Native)': 'تطوير تطبيقات الهاتف المحمول (رياكت نيتف)',
    'UI/UX Design Masterclass': 'ورشة تصميم واجهة المستخدم وتجربة المستخدم',
    'Cloud Computing with AWS': 'الحوسبة السحابية مع إيه دبليو إس',
    'Full Stack Web Development Bootcamp': 'معسكر تطوير الويب الشامل',

    // Course Levels
    'Advanced': 'متقدم',
    'Beginner': 'مبتدئ',
    'Intermediate': 'متوسط',

    // Course Descriptions
    'Master data analysis, visualization, and machine learning with Python. This comprehensive course covers everything from basic statistics to advanced machine learning algorithms.': 'أتقن تحليل البيانات والتصور والتعلم الآلي مع بايثون. تغطي هذه الدورة الشاملة كل شيء من الإحصاءات الأساسية إلى خوارزميات التعلم الآلي المتقدمة.',
    'Given the increasing demand for data scientists in the region, this course will significantly enhance your career prospects. Your technical background makes you a perfect fit.': 'نظراً للطلب المتزايد على علماء البيانات في المنطقة، ستساعد هذه الدورة في تعزيز آفاقك المهنية بشكل كبير. خلفيتك التقنية تجعلك مناسباً تماماً.',
    'Learn essential cybersecurity concepts and practical skills to protect digital assets and understand security threats.': 'تعلم مفاهيم الأمن السيبراني الأساسية والمهارات العملية لحماية الأصول الرقمية وفهم التهديدات الأمنية.',
    'Given the increasing digital transformation in Gulf countries, cybersecurity expertise is in extremely high demand. Your technical background makes you a perfect fit.': 'نظراً للتحول الرقمي المتزايد في دول الخليج، خبرة الأمن السيبراني مطلوبة بشدة. خلفيتك التقنية تجعلك مناسباً تماماً.',
    'Build cross-platform mobile applications using React Native. Learn to create apps for both iOS and Android platforms.': 'أنشئ تطبيقات الهاتف المحمول متعددة المنصات باستخدام رياكت نيتف. تعلم إنشاء تطبيقات لمنصات آي أو إس وأندرويد.',
    'Mobile development is one of the fastest-growing fields in tech. Your JavaScript knowledge will give you a head start in React Native development.': 'تطوير الهاتف المحمول هو أحد أسرع المجالات نمواً في التكنولوجيا. معرفتك بجافا سكريبت ستمنحك بداية مبكرة في تطوير رياكت نيتف.',
    'Master user interface and user experience design principles. Learn to create intuitive and beautiful digital experiences.': 'أتقن مبادئ تصميم واجهة المستخدم وتجربة المستخدم. تعلم إنشاء تجارب رقمية بديهية وجميلة.',
    'Design skills are increasingly valuable in the tech industry. This course will complement your technical skills and open new career opportunities.': 'مهارات التصميم أصبحت أكثر قيمة في صناعة التكنولوجيا. ستكمل هذه الدورة مهاراتك التقنية وتمنحك فرص مهنية جديدة.',
    'Learn cloud architecture and AWS services to deploy and manage applications in the cloud.': 'تعلم هندسة السحابة وخدمات إيه دبليو إس لنشر وإدارة التطبيقات في السحابة.',
    'Cloud computing skills are essential for modern software development. This course will prepare you for cloud-based roles.': 'مهارات الحوسبة السحابية ضرورية لتطوير البرمجيات الحديثة. ستعدك هذه الدورة للدور القائمة على السحابة.',
    'Complete web development course covering frontend and backend technologies. Build full-stack applications from scratch.': 'دورة تطوير الويب الشاملة التي تغطي تقنيات الواجهة الأمامية والخلفية. أنشئ تطبيقات شاملة من الصفر.',
    'Full-stack developers are in high demand. This comprehensive course will prepare you for modern web development roles.': 'مطوري الويب الشامل مطلوبون بشدة. ستعدك هذه الدورة الشاملة لأدوار تطوير الويب الحديثة.',

    // Course Skills
    'Data Analysis': 'تحليل البيانات',
    'Machine Learning': 'التعلم الآلي',
    'Python Programming': 'برمجة بايثون',
    'Statistical Modeling': 'النمذجة الإحصائية',
    'Network security protocols': 'بروتوكولات أمن الشبكات',
    'Threat assessment': 'تقييم التهديدات',
    'Security tools': 'أدوات الأمان',
    'Incident response': 'الاستجابة للحوادث',
    'React Native': 'رياكت نيتف',
    'Mobile UI/UX': 'واجهة وتجربة المستخدم للهاتف المحمول',
    'Cross-platform development': 'التطوير متعدد المنصات',
    'App deployment': 'نشر التطبيقات',
    'User Research': 'بحث المستخدم',
    'Wireframing': 'إنشاء الإطارات السلكية',
    'Prototyping': 'إنشاء النماذج الأولية',
    'Design Systems': 'أنظمة التصميم',
    'AWS Services': 'خدمات إيه دبليو إس',
    'Cloud Architecture': 'هندسة السحابة',
    'DevOps': 'ديف أوبس',
    'Infrastructure as Code': 'البنية التحتية كرمز',
    'HTML/CSS': 'إتش تي إم إل/سي إس إس',
    'JavaScript': 'جافا سكريبت',
    'Node.js': 'نود جي إس',
    'Database Design': 'تصميم قواعد البيانات',

    // Course Outline Titles
    'Introduction to Data Science': 'مقدمة في علم البيانات',
    'Python for Data Analysis': 'بايثون لتحليل البيانات',
    'Machine Learning Fundamentals': 'أساسيات التعلم الآلي',
    'Introduction to Cybersecurity': 'مقدمة في الأمن السيبراني',
    'Network Security': 'أمن الشبكات',
    'Security Tools and Practices': 'أدوات وممارسات الأمان',
    'React Native Basics': 'أساسيات رياكت نيتف',
    'Mobile UI Development': 'تطوير واجهة الهاتف المحمول',
    'App Deployment': 'نشر التطبيقات',
    'Design Fundamentals': 'أساسيات التصميم',
    'User Research': 'بحث المستخدم',
    'Prototyping': 'إنشاء النماذج الأولية',
    'AWS Fundamentals': 'أساسيات إيه دبليو إس',
    'Cloud Architecture': 'هندسة السحابة',
    'DevOps Practices': 'ممارسات ديف أوبس',
    'Frontend Development': 'تطوير الواجهة الأمامية',
    'Backend Development': 'تطوير الخلفية',
    'Database Design': 'تصميم قواعد البيانات',
    'Full Stack Integration': 'تكامل الواجهة الشاملة',

    // Course Outline Descriptions
    'Overview of data science concepts and tools': 'نظرة عامة على مفاهيم وأدوات علم البيانات',
    'Learn pandas, numpy, and matplotlib': 'تعلم بانداس ونمباي وماتبلوت',
    'Supervised and unsupervised learning algorithms': 'خوارزميات التعلم الموجه وغير الموجه',
    'Basic concepts and threat landscape': 'المفاهيم الأساسية ومشهد التهديدات',
    'Understanding network vulnerabilities and protection': 'فهم نقاط الضعف في الشبكة والحماية',
    'Hands-on experience with security tools': 'خبرة عملية مع أدوات الأمان',
    'Introduction to React Native framework': 'مقدمة في إطار عمل رياكت نيتف',
    'Creating responsive mobile interfaces': 'إنشاء واجهات هاتف محمول متجاوبة',
    'Publishing to app stores': 'النشر في متاجر التطبيقات',
    'Principles of good design': 'مبادئ التصميم الجيد',
    'Understanding user needs and behaviors': 'فهم احتياجات وسلوكيات المستخدم',
    'Creating interactive prototypes': 'إنشاء نماذج أولية تفاعلية',
    'Introduction to AWS services': 'مقدمة في خدمات إيه دبليو إس',
    'Designing scalable cloud solutions': 'تصميم حلول سحابية قابلة للتطوير',
    'CI/CD and automation': 'التكامل المستمر والنشر المستمر والأتمتة',
    'HTML, CSS, and JavaScript fundamentals': 'أساسيات إتش تي إم إل وسي إس إس وجافا سكريبت',
    'Server-side programming with Node.js': 'البرمجة من جانب الخادم مع نود جي إس',
    'Database modeling and SQL': 'نمذجة قواعد البيانات وإس كيو إل',
    'Connecting frontend and backend': 'ربط الواجهة الأمامية والخلفية',

    // Course Prerequisites
    'Basic programming knowledge': 'معرفة أساسية بالبرمجة',
    'Understanding of mathematics and statistics': 'فهم الرياضيات والإحصاء',
    'Familiarity with Python basics': 'الإلمام بأساسيات بايثون',
    'Basic computer knowledge': 'معرفة أساسية بالحاسوب',
    'Understanding of networking concepts': 'فهم مفاهيم الشبكات',
    'No prior security experience required': 'لا توجد خبرة أمنية مطلوبة مسبقاً',
    'JavaScript knowledge': 'معرفة جافا سكريبت',
    'Basic React understanding': 'فهم أساسي لرياكت',
    'Familiarity with mobile apps': 'الإلمام بتطبيقات الهاتف المحمول',
    'No prior design experience required': 'لا توجد خبرة تصميم مطلوبة مسبقاً',
    'Basic computer skills': 'مهارات حاسوب أساسية',
    'Creative mindset': 'عقلية إبداعية',
    'Understanding of web technologies': 'فهم تقنيات الويب',
    'Familiarity with command line': 'الإلمام بسطر الأوامر',
    'No prior programming experience required': 'لا توجد خبرة برمجة مطلوبة مسبقاً',
    'Willingness to learn and practice': 'الرغبة في التعلم والممارسة',

    // Course Categories
    'Mobile Development': 'تطوير الهاتف المحمول',
    'UI/UX Design': 'تصميم واجهة المستخدم وتجربة المستخدم',
    'DevOps': 'ديف أوبس',
    'Web Development': 'تطوير الويب',

    // Common
    'Error': 'خطأ',
    'Success': 'نجح',
    'OK': 'موافق',
    'Loading...': 'جاري التحميل...',
    'Failed to pick image. Please try again.': 'فشل في اختيار الصورة. يرجى المحاولة مرة أخرى.',
    'Cancel': 'إلغاء',
    'Sign out of your account': 'تسجيل الخروج من حسابك',
    'Account': 'الحساب',
    'Edit Profile': 'تعديل الملف الشخصي',
    'Update your personal information': 'تحديث معلوماتك الشخصية',
    'Change Password': 'تغيير كلمة المرور',
    'Update your password': 'تحديث كلمة المرور',

    // Profile Photo Upload
    'Profile Photo': 'صورة الملف الشخصي',
    'Choose how to update your profile photo': 'اختر كيفية تحديث صورة ملفك الشخصي',
    'Take Photo': 'التقاط صورة',
    'Choose from Gallery': 'اختيار من المعرض',
    'Remove Photo': 'إزالة الصورة',
    'Permission required': 'الإذن مطلوب',
    'You need to allow access to your photos to upload an image.': 'تحتاج إلى السماح بالوصول إلى صورك لرفع صورة.',
    'You need to allow access to your camera to take a photo.': 'تحتاج إلى السماح بالوصول إلى الكاميرا لالتقاط صورة.',
    'Failed to pick image.': 'فشل في اختيار الصورة.',
    'Failed to take photo.': 'فشل في التقاط الصورة.',
    'Failed to save profile photo locally.': 'فشل في حفظ صورة الملف الشخصي محلياً.',
    'Profile photo updated successfully!': 'تم تحديث صورة الملف الشخصي بنجاح!',
    'Are you sure you want to remove your profile photo?': 'هل أنت متأكد من أنك تريد إزالة صورة ملفك الشخصي؟',
    'Failed to remove profile photo.': 'فشل في إزالة صورة الملف الشخصي.',
    'Profile photo removed!': 'تم إزالة صورة الملف الشخصي!',
  };

  const t = (key) => {
    if (language === 'Arabic') {
      return translations[key] || key;
    } else {
      return key; // Return original English text
    }
  };

  const value = {
    language,
    toggleLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}; 