// Job Generator Service - Provides fallback job data
// This generates jobs similar to real job listings

const companies = [
  'TechCorp Middle East',
  'Digital Solutions Arabia',
  'Innovation Hub Qatar',
  'Smart Systems Kuwait',
  'Future Tech UAE',
  'Digital Dynamics Bahrain',
  'TechVision Oman',
  'Innovation Labs Saudi',
  'Digital Bridge Palestine',
  'TechConnect Jordan'
];

const jobTitles = [
  'Software Developer',
  'Data Analyst',
  'Cybersecurity Specialist',
  'UI/UX Designer',
  'Project Manager',
  'Business Analyst',
  'Network Administrator',
  'Mobile App Developer',
  'Cloud Engineer',
  'DevOps Engineer',
  'AI/ML Engineer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'Database Administrator',
  'IT Consultant',
  'System Administrator',
  'Quality Assurance Engineer',
  'Product Manager',
  'Technical Lead',
  'Data Scientist',
  'Machine Learning Engineer',
  'Blockchain Developer',
  'Game Developer',
  'Robotics Engineer',
  'IoT Developer',
  'Computer Vision Engineer',
  'Natural Language Processing Engineer',
  'Big Data Engineer',
  'Data Engineer',
  'Business Intelligence Analyst',
  'Digital Marketing Specialist',
  'Content Creator',
  'Social Media Manager',
  'SEO Specialist',
  'Marketing Analyst',
  'Brand Manager',
  'Event Coordinator',
  'Human Resources Manager',
  'Recruitment Specialist',
  'Talent Acquisition Specialist',
  'Financial Analyst',
  'Investment Analyst',
  'Risk Manager',
  'Compliance Officer',
  'Legal Consultant',
  'Healthcare Administrator',
  'Nurse Practitioner',
  'Medical Technologist',
  'Pharmaceutical Sales Representative',
  'Environmental Scientist',
  'Sustainability Consultant',
  'Energy Analyst',
  'Supply Chain Manager',
  'Logistics Coordinator',
  'Procurement Specialist',
  'Operations Manager',
  'Customer Success Manager',
  'Sales Representative',
  'Account Manager',
  'Business Development Manager',
  'Strategy Consultant',
  'Management Consultant',
  'Change Management Specialist',
  'Organizational Development Specialist',
  'Training Coordinator',
  'Instructional Designer',
  'Educational Technology Specialist',
  'Academic Advisor',
  'Research Analyst',
  'Market Research Analyst',
  'User Experience Researcher',
  'Information Architect',
  'Technical Writer',
  'Content Strategist',
  'Copywriter',
  'Graphic Designer',
  'Visual Designer',
  'Motion Graphics Designer',
  '3D Artist',
  'Video Editor',
  'Photographer',
  'Interior Designer',
  'Fashion Designer',
  'Industrial Designer',
  'Architect',
  'Civil Engineer',
  'Mechanical Engineer',
  'Electrical Engineer',
  'Chemical Engineer',
  'Biomedical Engineer',
  'Aerospace Engineer',
  'Petroleum Engineer',
  'Mining Engineer',
  'Environmental Engineer',
  'Structural Engineer',
  'Transportation Engineer',
  'Water Resources Engineer',
  'Geotechnical Engineer',
  'Construction Manager',
  'Real Estate Agent',
  'Property Manager',
  'Facility Manager',
  'Security Manager',
  'Risk Analyst',
  'Insurance Underwriter',
  'Claims Adjuster',
  'Actuary',
  'Auditor',
  'Tax Consultant',
  'Forensic Accountant',
  'Cost Accountant',
  'Management Accountant',
  'Treasury Analyst',
  'Credit Analyst',
  'Loan Officer',
  'Investment Banker',
  'Portfolio Manager',
  'Quantitative Analyst',
  'Derivatives Trader',
  'Commodity Trader',
  'Foreign Exchange Trader',
  'Stock Broker',
  'Financial Planner',
  'Wealth Manager',
  'Estate Planner',
  'Insurance Agent',
  'Reinsurance Specialist',
  'Pension Administrator',
  'Benefits Administrator',
  'Compensation Analyst',
  'Labor Relations Specialist',
  'Employment Law Specialist',
  'Workplace Safety Specialist',
  'Occupational Health Specialist',
  'Industrial Hygienist',
  'Environmental Health Specialist',
  'Public Health Specialist',
  'Epidemiologist',
  'Biostatistician',
  'Clinical Research Coordinator',
  'Medical Device Sales Representative',
  'Pharmaceutical Research Scientist',
  'Biotechnology Researcher',
  'Genetic Counselor',
  'Nutritionist',
  'Dietitian',
  'Physical Therapist',
  'Occupational Therapist',
  'Speech Language Pathologist',
  'Respiratory Therapist',
  'Radiologic Technologist',
  'Medical Laboratory Technician',
  'Pharmacy Technician',
  'Dental Hygienist',
  'Optometrist',
  'Veterinarian',
  'Veterinary Technician',
  'Animal Care Specialist',
  'Wildlife Biologist',
  'Marine Biologist',
  'Conservation Scientist',
  'Forestry Technician',
  'Agricultural Scientist',
  'Soil Scientist',
  'Horticulturist',
  'Landscape Architect',
  'Urban Planner',
  'Transportation Planner',
  'Regional Planner',
  'Demographer',
  'Sociologist',
  'Anthropologist',
  'Archaeologist',
  'Historian',
  'Political Scientist',
  'Economist',
  'Statistician',
  'Mathematician',
  'Physicist',
  'Chemist',
  'Biologist',
  'Geologist',
  'Meteorologist',
  'Astronomer',
  'Oceanographer',
  'Seismologist',
  'Volcanologist',
  'Paleontologist',
  'Zoologist',
  'Botanist',
  'Microbiologist',
  'Immunologist',
  'Neurologist',
  'Cardiologist',
  'Oncologist',
  'Dermatologist',
  'Psychiatrist',
  'Psychologist',
  'Counselor',
  'Social Worker',
  'Therapist',
  'Rehabilitation Specialist',
  'Substance Abuse Counselor',
  'Mental Health Specialist',
  'Child Development Specialist',
  'Geriatric Care Specialist',
  'Hospice Care Specialist',
  'Palliative Care Specialist',
  'Emergency Medical Technician',
  'Paramedic',
  'Firefighter',
  'Police Officer',
  'Security Guard',
  'Private Investigator',
  'Forensic Scientist',
  'Crime Scene Investigator',
  'Coroner',
  'Medical Examiner',
  'Pathologist',
  'Toxicologist',
  'DNA Analyst',
  'Fingerprint Analyst',
  'Ballistics Expert',
  'Document Examiner',
  'Computer Forensics Specialist',
  'Digital Forensics Analyst',
  'Cybercrime Investigator',
  'Fraud Investigator',
  'Compliance Investigator',
  'Internal Auditor',
  'External Auditor',
  'Government Auditor',
  'Performance Auditor',
  'IT Auditor',
  'Security Auditor',
  'Privacy Officer',
  'Data Protection Officer',
  'Information Security Officer',
  'Chief Information Security Officer',
  'Chief Technology Officer',
  'Chief Information Officer',
  'Chief Data Officer',
  'Chief Analytics Officer',
  'Chief Digital Officer',
  'Chief Innovation Officer',
  'Chief Strategy Officer',
  'Chief Operating Officer',
  'Chief Financial Officer',
  'Chief Executive Officer',
  'President',
  'Vice President',
  'Director',
  'Manager',
  'Supervisor',
  'Coordinator',
  'Specialist',
  'Analyst',
  'Assistant',
  'Clerk',
  'Receptionist',
  'Administrative Assistant',
  'Executive Assistant',
  'Office Manager',
  'Secretary',
  'Data Entry Specialist',
  'Records Manager',
  'Document Controller',
  'Quality Control Specialist',
  'Production Supervisor',
  'Manufacturing Engineer',
  'Process Engineer',
  'Quality Engineer',
  'Reliability Engineer',
  'Maintenance Engineer',
  'Field Service Engineer',
  'Application Engineer',
  'Sales Engineer',
  'Pre-Sales Engineer',
  'Post-Sales Engineer',
  'Customer Support Specialist',
  'Technical Support Specialist',
  'Help Desk Specialist',
  'Desktop Support Specialist',
  'Network Support Specialist',
  'Database Support Specialist',
  'Application Support Specialist',
  'Infrastructure Support Specialist',
  'Cloud Support Specialist',
  'Security Support Specialist',
  'Compliance Support Specialist',
  'Regulatory Affairs Specialist',
  'Clinical Affairs Specialist',
  'Medical Affairs Specialist',
  'Scientific Affairs Specialist',
  'Regulatory Compliance Specialist',
  'Quality Assurance Specialist',
  'Quality Control Specialist',
  'Laboratory Technician',
  'Research Technician',
  'Laboratory Assistant',
  'Research Assistant',
  'Teaching Assistant',
  'Graduate Assistant',
  'Research Associate',
  'Postdoctoral Researcher',
  'Research Scientist',
  'Principal Investigator',
  'Research Director',
  'Laboratory Director',
  'Clinical Director',
  'Medical Director',
  'Scientific Director',
  'Technical Director',
  'Creative Director',
  'Art Director',
  'Design Director',
  'Marketing Director',
  'Sales Director',
  'Operations Director',
  'Human Resources Director',
  'Finance Director',
  'Legal Director',
  'Compliance Director',
  'Risk Director',
  'Security Director',
  'Information Technology Director',
  'Research and Development Director',
  'Product Development Director',
  'Business Development Director',
  'Strategic Planning Director',
  'Corporate Communications Director',
  'Public Relations Director',
  'Investor Relations Director',
  'Customer Experience Director',
  'Digital Transformation Director',
  'Innovation Director',
  'Sustainability Director',
  'Diversity and Inclusion Director',
  'Corporate Social Responsibility Director',
  'Environmental Health and Safety Director',
  'Facilities Director',
  'Procurement Director',
  'Supply Chain Director',
  'Logistics Director',
  'Transportation Director',
  'Distribution Director',
  'Warehouse Director',
  'Inventory Director',
  'Asset Management Director',
  'Property Management Director',
  'Real Estate Director',
  'Construction Director',
  'Engineering Director',
  'Architecture Director',
  'Design Director',
  'Creative Services Director',
  'Brand Director',
  'Advertising Director',
  'Media Director',
  'Communications Director',
  'Content Director',
  'Editorial Director',
  'Publishing Director',
  'Production Director',
  'Post-Production Director',
  'Broadcasting Director',
  'Journalism Director',
  'News Director',
  'Sports Director',
  'Entertainment Director',
  'Events Director',
  'Hospitality Director',
  'Tourism Director',
  'Travel Director',
  'Airlines Director',
  'Cruise Director',
  'Hotel Director',
  'Restaurant Director',
  'Catering Director',
  'Food Service Director',
  'Culinary Director',
  'Chef',
  'Sous Chef',
  'Pastry Chef',
  'Baker',
  'Butcher',
  'Fishmonger',
  'Greengrocer',
  'Deli Clerk',
  'Grocery Clerk',
  'Stock Clerk',
  'Inventory Clerk',
  'Shipping Clerk',
  'Receiving Clerk',
  'Order Picker',
  'Forklift Operator',
  'Truck Driver',
  'Delivery Driver',
  'Courier',
  'Mail Carrier',
  'Postal Worker',
  'Package Handler',
  'Warehouse Worker',
  'Assembly Line Worker',
  'Machine Operator',
  'Quality Inspector',
  'Production Worker',
  'Manufacturing Worker',
  'Factory Worker',
  'Industrial Worker',
  'Construction Worker',
  'Carpenter',
  'Electrician',
  'Plumber',
  'HVAC Technician',
  'Welder',
  'Machinist',
  'Tool and Die Maker',
  'Millwright',
  'Boilermaker',
  'Ironworker',
  'Roofer',
  'Mason',
  'Tile Setter',
  'Painter',
  'Glazier',
  'Insulator',
  'Sheet Metal Worker',
  'Pipefitter',
  'Steamfitter',
  'Sprinkler Fitter',
  'Elevator Mechanic',
  'Escalator Mechanic',
  'Refrigeration Mechanic',
  'Automotive Mechanic',
  'Diesel Mechanic',
  'Heavy Equipment Mechanic',
  'Small Engine Mechanic',
  'Motorcycle Mechanic',
  'Bicycle Mechanic',
  'Watchmaker',
  'Jeweler',
  'Goldsmith',
  'Silversmith',
  'Blacksmith',
  'Farrier',
  'Saddler',
  'Leatherworker',
  'Bookbinder',
  'Printmaker',
  'Engraver',
  'Etcher',
  'Lithographer',
  'Screen Printer',
  'Sign Maker',
  'Glassblower',
  'Potter',
  'Ceramicist',
  'Sculptor',
  'Carver',
  'Woodworker',
  'Cabinetmaker',
  'Furniture Maker',
  'Upholsterer',
  'Tailor',
  'Seamstress',
  'Dressmaker',
  'Pattern Maker',
  'Fashion Designer',
  'Costume Designer',
  'Textile Designer',
  'Fabric Designer',
  'Colorist',
  'Dyer',
  'Bleacher',
  'Finisher',
  'Weaver',
  'Spinner',
  'Knitter',
  'Crocheter',
  'Embroiderer',
  'Quilter',
  'Lacemaker',
  'Tatting',
  'Macrame',
  'Basket Weaver',
  'Rug Maker',
  'Carpet Weaver',
  'Tapestry Weaver',
  'Gobelin Weaver',
  'Jacquard Weaver',
  'Dobby Weaver',
  'Shuttle Loom Weaver',
  'Rapier Loom Weaver',
  'Air Jet Loom Weaver',
  'Water Jet Loom Weaver',
  'Projectile Loom Weaver',
  'Circular Loom Weaver',
  'Narrow Fabric Weaver',
  'Broad Fabric Weaver',
  'Technical Textile Weaver',
  'Industrial Textile Weaver',
  'Home Textile Weaver',
  'Fashion Textile Weaver',
  'Interior Textile Weaver',
  'Automotive Textile Weaver',
  'Medical Textile Weaver',
  'Geotextile Weaver',
  'Agrotextile Weaver',
  'Buildtech Weaver',
  'Clothtech Weaver',
  'Geotech Weaver',
  'Hometech Weaver',
  'Indutech Weaver',
  'Medtech Weaver',
  'Mobiltech Weaver',
  'Oekotech Weaver',
  'Packtech Weaver',
  'Protech Weaver',
  'Sportech Weaver',
  'Transportech Weaver'
];

const locations = [
  'Dubai, UAE',
  'Riyadh, Saudi Arabia',
  'Doha, Qatar',
  'Kuwait City, Kuwait',
  'Muscat, Oman',
  'Manama, Bahrain',
  'Amman, Jordan',
  'Ramallah, Palestine',
  'Abu Dhabi, UAE',
  'Jeddah, Saudi Arabia'
];

const jobDescriptions = [
  'Join our dynamic team to develop innovative software solutions for the Middle East market. Experience with modern technologies and agile methodologies required.',
  'Analyze complex data sets to provide actionable insights for business growth. Strong analytical skills and experience with data visualization tools needed.',
  'Protect our digital infrastructure and implement security best practices. Experience with cybersecurity frameworks and threat detection required.',
  'Create intuitive and beautiful user experiences for web and mobile applications. Strong portfolio and experience with design tools essential.',
  'Lead cross-functional teams to deliver high-quality software projects on time and within budget. PMP certification preferred.',
  'Bridge the gap between business needs and technical solutions. Strong communication skills and business acumen required.',
  'Maintain and optimize network infrastructure for optimal performance and security. CCNA certification preferred.',
  'Develop cutting-edge mobile applications for iOS and Android platforms. Experience with React Native or Flutter required.',
  'Design and implement cloud-based solutions using AWS, Azure, or Google Cloud. Cloud certifications preferred.',
  'Automate deployment processes and maintain CI/CD pipelines. Experience with Docker and Kubernetes required.'
];

const generateRandomJob = (index) => {
  const company = companies[Math.floor(Math.random() * companies.length)];
  let title = jobTitles[Math.floor(Math.random() * jobTitles.length)];
  const location = locations[Math.floor(Math.random() * locations.length)];
  const description = jobDescriptions[Math.floor(Math.random() * jobDescriptions.length)];
  const salary = Math.floor(Math.random() * (15000 - 5000 + 1)) + 5000;
  const workType = ['Remote', 'On-site', 'Hybrid'][Math.floor(Math.random() * 3)];
  const level = ['Entry Level', 'Mid Level', 'Senior Level'][Math.floor(Math.random() * 3)];
  const category = ['Technology', 'Data Science', 'Cybersecurity', 'Design', 'Management'][Math.floor(Math.random() * 5)];

  // Add variations to job titles to make them more diverse
  const titleVariations = [
    `${title}`,
    `${title} Specialist`,
    `${title} Engineer`,
    `${title} Developer`,
    `${title} Analyst`,
    `${title} Consultant`,
    `${title} Manager`,
    `${title} Lead`,
    `${title} Coordinator`,
    `${title} Administrator`
  ];
  
  title = titleVariations[Math.floor(Math.random() * titleVariations.length)];

  return {
    id: `job_${Date.now()}_${index}`,
    title: title,
    company: company,
    location: location,
    description: description,
    salary: `$${salary.toLocaleString()}`,
    workType: workType,
    level: level,
    category: category,
    image: `https://source.unsplash.com/400x400/?${company.split(' ')[0]},logo`,
    job_url: `https://example.com/jobs/${title.toLowerCase().replace(/\s+/g, '-')}`,
  };
};

export const generateJobCatalog = () => {
  const jobs = [];
  for (let i = 0; i < 50; i++) {
    jobs.push(generateRandomJob(i));
  }
  return jobs;
};

export const searchJobs = (searchTerm) => {
  const allJobs = generateJobCatalog();
  const searchLower = searchTerm.toLowerCase();
  
  return allJobs.filter(job => 
    job.title.toLowerCase().includes(searchLower) ||
    job.company.toLowerCase().includes(searchLower) ||
    job.description.toLowerCase().includes(searchLower) ||
    job.category.toLowerCase().includes(searchLower)
  );
};

export const getJobsByCategory = (category) => {
  const allJobs = generateJobCatalog();
  return allJobs.filter(job => job.category === category);
}; 